function [z_opt, z_alt_opt] = Varshney(z, idx_comm, idx_radar, varargin)
%VARSHNEY Wrapper around the original unit-modulus Varshney OFDM solver.
%   The original algorithm assumes every subcarrier has unit magnitude.
%   This wrapper keeps that assumption inside the optimization, then maps
%   the optimized radar phases back to the input magnitude allocation so the
%   result can be evaluated in the main simulation with its original energy
%   split between communication and radar subcarriers.
%
%   OutputMode='raw' reproduces the earlier legacy version used in the
%   ISL sidelobe plots: the function returns the raw unit-modulus solution.
%   OutputMode='mapped' returns the newer amplitude-preserving wrapper.
%
%   Inputs:
%       z         - Input frequency-domain codeword generated by the main
%                   simulation. Its amplitudes are preserved on output.
%       idx_comm  - Communication subcarrier indices.
%       idx_radar - Radar subcarrier indices.
%
%   Outputs:
%       z_opt      - Optimized codeword mapped back to the input magnitudes.
%       z_unit_opt - Raw unit-modulus codeword produced by the original
%                    Varshney optimization.

opts = local_parse_options(z, idx_comm, idx_radar, varargin{:});

z_input = opts.z;
amp_input = abs(z_input);

% Build a unit-modulus codeword for the original Varshney algorithm.
z_unit_in = exp(1j * angle(z_input));
small_mask = amp_input < opts.tol_mag | ~isfinite(amp_input);
if any(small_mask)
    z_unit_in(small_mask) = exp(1j * 2 * pi * rand(sum(small_mask), 1));
end

% Run the original unit-modulus optimization core.
z_unit_opt = local_varshney_unitmod_core(z_unit_in, opts);

% Map the optimized radar phases back to the original amplitude allocation.
z_mapped_opt = z_input;
if ~isempty(opts.idx_radar)
    z_mapped_opt(opts.idx_radar) = amp_input(opts.idx_radar) .* ...
        exp(1j * angle(z_unit_opt(opts.idx_radar)));

    zero_radar = amp_input(opts.idx_radar) < opts.tol_mag | ...
        ~isfinite(amp_input(opts.idx_radar));
    if any(zero_radar)
        z_mapped_opt(opts.idx_radar(zero_radar)) = z_input(opts.idx_radar(zero_radar));
    end
end

% Keep communication symbols exactly as generated by the main simulation.
z_mapped_opt(opts.idx_comm) = z_input(opts.idx_comm);

switch lower(string(opts.outputMode))
    case "raw"
        z_opt = z_unit_opt;
        z_alt_opt = z_mapped_opt;
    case "mapped"
        z_opt = z_mapped_opt;
        z_alt_opt = z_unit_opt;
    otherwise
        error('Varshney:BadOutputMode', ...
            'OutputMode must be ''raw'' or ''mapped''.');
end

end

function z_unit_opt = local_varshney_unitmod_core(z, opts)
%LOCAL_VARSHNEY_UNITMOD_CORE Original unit-modulus Varshney iteration.

idx_comm = opts.idx_comm;
idx_radar = opts.idx_radar;
N = opts.N;
maxIt = opts.maxIt;
epsStop = opts.epsStop;
tol_mag = opts.tol_mag;
lambda2 = opts.lambda2;
verbose = opts.verbose;

zc = z(idx_comm);

FH = @(v) ifft(v(:)) * sqrt(N);
Fmat = dftmtx(N) / sqrt(N);
papr_fun = @(x) max(abs(x).^2) / mean(abs(x).^2);

x = FH(z);
PAPR_prev = papr_fun(x);

for t = 1:maxIt
    s = FH(z);
    FS = Fmat .* repmat(s.', N, 1);
    Q = 2 * (FS - repmat(z, 1, N));
    c_vec = real(N - 0.5 * (conj(z).' * Q));
    Qr = Q(idx_radar, :);

    ok = false;
    w = [];
    try
        cvx_begin quiet
            cvx_precision best
            variable w(N) nonnegative
            minimize(norm(Qr * w, 1) - c_vec * w + lambda2 * sum_square(w))
            subject to
                sum(w) == 1
        cvx_end
        ok = (strcmpi(cvx_status, 'Solved') || strcmpi(cvx_status, 'Inaccurate/Solved')) ...
            && all(isfinite(w));
    catch
        ok = false;
    end

    if ~ok
        score = real(conj(z).' * Q) + c_vec;
        [~, nstar] = max(score);
        w = zeros(N, 1);
        w(nstar) = 1;
    end

    q_w = Q * w;
    q_w_r = q_w(idx_radar);

    keep_mask = abs(q_w_r) < tol_mag | ~isfinite(q_w_r);
    zr_new = -exp(1j * angle(q_w_r));
    if any(keep_mask)
        zr_new(keep_mask) = z(idx_radar(keep_mask));
    end

    z = complex(zeros(N, 1));
    z(idx_comm) = zc;
    z(idx_radar) = zr_new;

    valid_now = abs(z) >= tol_mag;
    z(valid_now) = z(valid_now) ./ abs(z(valid_now));
    if any(~valid_now)
        z(~valid_now) = exp(1j * 2 * pi * rand(sum(~valid_now), 1));
    end

    x = FH(z);
    PAPR_curr = papr_fun(x);
    rel = abs(PAPR_curr - PAPR_prev) / max(PAPR_prev, eps);

    if verbose
        fallback_tag = '';
        if ~ok
            fallback_tag = ' [fallback]';
        end
        fprintf('  [Varshney] iter %3d/%d: PAPR = %.4f dB, rel_err = %.2e%s\n', ...
            t, maxIt, 10 * log10(PAPR_curr), rel, fallback_tag);
    end

    if rel <= epsStop
        break;
    end
    PAPR_prev = PAPR_curr;
end

z_unit_opt = z;

end

function opts = local_parse_options(z, idx_comm, idx_radar, varargin)
%LOCAL_PARSE_OPTIONS Validate inputs and parse name-value pairs.

p = inputParser;
addRequired(p, 'z', @(x) isnumeric(x) && isvector(x));
addRequired(p, 'idx_comm', @(x) isnumeric(x) && isvector(x));
addRequired(p, 'idx_radar', @(x) isnumeric(x) && isvector(x));
addParameter(p, 'maxIt', 10, @(x) isscalar(x) && x > 0 && mod(x, 1) == 0);
addParameter(p, 'epsStop', 1e-5, @(x) isscalar(x) && x > 0);
addParameter(p, 'tol_mag', 1e-12, @(x) isscalar(x) && x >= 0);
addParameter(p, 'lambda2', 1e-10, @(x) isscalar(x) && x >= 0);
addParameter(p, 'OutputMode', 'mapped', @(x) ischar(x) || isstring(x));
addParameter(p, 'verbose', false, @islogical);
parse(p, z, idx_comm, idx_radar, varargin{:});

opts = struct();
opts.z = p.Results.z(:);
opts.idx_comm = p.Results.idx_comm(:);
opts.idx_radar = p.Results.idx_radar(:);
opts.N = numel(opts.z);
opts.maxIt = p.Results.maxIt;
opts.epsStop = p.Results.epsStop;
opts.tol_mag = p.Results.tol_mag;
opts.lambda2 = p.Results.lambda2;
opts.outputMode = lower(string(p.Results.OutputMode));
opts.verbose = p.Results.verbose;

if any(mod(opts.idx_comm, 1) ~= 0) || any(opts.idx_comm < 1) || any(opts.idx_comm > opts.N)
    error('Varshney: idx_comm must contain integer indices in [1, N].');
end

if any(mod(opts.idx_radar, 1) ~= 0) || any(opts.idx_radar < 1) || any(opts.idx_radar > opts.N)
    error('Varshney: idx_radar must contain integer indices in [1, N].');
end

if ~isempty(intersect(opts.idx_comm, opts.idx_radar))
    error('Varshney: idx_comm and idx_radar must not overlap.');
end

end
